### PR TITLE
Added offline-capable snippet (HTMLSnippetOffline)

### PR DESCRIPTION
**Pull request by tieniber**
Added an offline-capable HTMLSnippet to the package. Same codebase, just no on-click microflow option. Also updated base with with define/require flow like the new boilerplate.

### CODE REVIEW

**Comment by tieniber** [comment]
@JelteMX, is the second widget unnecessary? I figured the modeler would throw an error if your widget had a microflow option, but apparently that's not the case?

**Comment by JelteMX** [comment]
Good question, not sure. If the app is an offline app, it should throw an error when you use a Microflow. I'll check with R&D.

**Comment by allardbrand** [comment]
Any updates on this? Would be great if these changes can be merged anytime soon.

**Comment by diego-antonelli** [comment]
@tieniber do you still need it?

**Comment by tieniber** [comment]
No, it’s not particularly relevant anymore.

**Pull request closed without merging**
